version: 2
updates:
# Update GitHub action commit SHAs
- package-ecosystem: "github-actions"
  directory: "/"
  groups:
    github-actions:
      patterns: ["*"]
  schedule:
    interval: "weekly"
  cooldown:
   default-days: 7
# Update NuGet dependencies
- package-ecosystem: "nuget"
  directories:
    - "/docs/**/snippets/**"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 5
  cooldown:
    default-days: 7 
  groups:
      nuget:
        patterns: ["*"]
        group-by: dependency-name
